[project]
name = "agent-runtime-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=1.2.15",
    "langchain-litellm>=0.2.0",
    "langgraph>=1.0.9",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "litellm>=1.82.6",
    "python-dotenv>=1.2.1",
    "rich>=14.3.3",
    "tiktoken>=0.12.0",
    "typer>=0.24.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
